-- Services
INSERT OR IGNORE INTO "ec_services" ("id","slug","status","created_at","updated_at","published_at","locale","title","description","duration","format","price","sort_order") VALUES
('service-prenatal','service-prenatal','published',datetime('now'),datetime('now'),datetime('now'),'en','Prenatal Lactation Consult','A personalized session to prepare you for feeding before your baby arrives. We review your history, answer questions, and create a plan that builds confidence for your early breastfeeding journey.','60 minutes','Virtual or In-Person','$175',1),
('service-in-home','service-in-home','published',datetime('now'),datetime('now'),datetime('now'),'en','In-Home Lactation Consult','Hands-on support in the comfort of your home. Assessment includes latch, positioning, feeding effectiveness, and a customized plan to help you reach your feeding goals.','60–90 minutes','In-Person','$300',2),
('service-follow-up','service-follow-up','published',datetime('now'),datetime('now'),datetime('now'),'en','Follow Up','A targeted visit to evaluate progress, adjust your care plan, and troubleshoot new or ongoing feeding concerns. Support designed to keep you moving forward with confidence.','45–60 minutes','In-Person','$200',3),
('service-back-to-work','service-back-to-work','published',datetime('now'),datetime('now'),datetime('now'),'en','Back To Work','Guidance to help you pump efficiently, maintain milk supply, and build a practical feeding and pumping schedule that fits your work life. Ideal for parents returning to work.','45–60 minutes','Virtual or In-Person','$175',4),
('service-after-loss','service-after-loss','published',datetime('now'),datetime('now'),datetime('now'),'en','Lactation After Loss','Compassionate support for families navigating lactation after pregnancy or infant loss. We discuss options, provide emotional care, and create a plan that aligns with your healing and personal needs.','Contact for details','Virtual or In-Person','No charge',5);

-- Testimonials
INSERT OR IGNORE INTO "ec_testimonials" ("id","slug","status","created_at","updated_at","published_at","locale","name","quote","role") VALUES
('testimonial-kaitlin-b','testimonial-kaitlin-b','published',datetime('now'),datetime('now'),datetime('now'),'en','Kaitlin B.','Lauren was such an incredible support during my breastfeeding journey with my third son. She helped me navigate a possible tongue tie, improve comfort, and confidently take next steps. She is thoughtful, thorough, and truly caring—and even brought activities to keep my older kids busy during our visits. I highly recommend her. Thanks to Lauren, I''m still breastfeeding my 6-month-old and hoping to make it a full year!','Mom of three');

-- FAQs
INSERT OR IGNORE INTO "ec_faqs" ("id","slug","status","created_at","updated_at","published_at","locale","question","answer") VALUES
('faq-1','faq-1','published',datetime('now'),datetime('now'),datetime('now'),'en','What does a lactation consultant do?','A lactation consultant provides expert support for breastfeeding families, offering education, troubleshooting, and personalized care plans for parents and babies. They help with latch, pain, milk supply, and advise on pumping and supplementation. An IBCLC stands for International Board Certified Lactation Consultant, and is the gold standard in lactation education and care.'),
('faq-2','faq-2','published',datetime('now'),datetime('now'),datetime('now'),'en','Does insurance cover lactation consultations?','Yes! Option 1: Check coverage prior to a consult by creating an account on TLN to submit insurance information. If approved, you can schedule an appointment via the TLN website. Option 2: I will provide you with a superbill, which you can submit to your insurance company after the visit for potential reimbursement. Please note that coverage is not guaranteed.'),
('faq-3','faq-3','published',datetime('now'),datetime('now'),datetime('now'),'en','Can I pay out of pocket?','Yes! I have many easy ways of taking payment.'),
('faq-4','faq-4','published',datetime('now'),datetime('now'),datetime('now'),'en','Travel Fee / Cancellation fee','Home visits further than a 20 mile drive will incur an additional travel fee of $50. There is also a 24-hour cancellation fee of $50.');
