INSERT INTO ec_posts (id, slug, status, title, excerpt, body, meta_title, meta_description, published_at) VALUES (
  7,
  'how-much-should-you-spend-on-marketing-in-2026',
  'published',
  'How Much Should You Spend on Marketing in 2026?',
  'Marketing budgets are one of the most common sources of anxiety for business owners, mostly because no one gives them a straight answer.',
  '[{"_type":"block","_key":"a991e9a4","style":"h2","children":[{"_type":"span","_key":"21eb33ff","text":"The Percentage Rule Is a Starting Point, Not an Answer"}]},{"_type":"block","_key":"6f38c525","style":"normal","children":[{"_type":"span","_key":"d1cde9b5","text":"The U.S. Small Business Administration recommends allocating 7 to 8 percent of revenue to marketing if you''re under $5 million in annual revenue."}]},{"_type":"block","_key":"31ea2272","style":"h2","children":[{"_type":"span","_key":"0e4207f4","text":"Growth Stage Changes Everything"}]},{"_type":"block","_key":"133694a9","style":"normal","children":[{"_type":"span","_key":"6cec9dd4","text":"A business that launched 18 months ago needs to spend more than a 10-year-old business with a full client roster."}]},{"_type":"block","_key":"b9e979fd","style":"h2","children":[{"_type":"span","_key":"cc3f1844","text":"Industry Matters More Than Most People Admit"}]},{"_type":"block","_key":"64b44534","style":"normal","children":[{"_type":"span","_key":"3ff945cd","text":"A dental practice competes in a local market of maybe 10 to 15 direct competitors. A SaaS company might compete against 200 alternatives."}]},{"_type":"block","_key":"9e2d23e6","style":"h2","children":[{"_type":"span","_key":"7aa8910e","text":"How to Allocate What You Spend"}]},{"_type":"block","_key":"60794dce","style":"normal","children":[{"_type":"span","_key":"8c80e9b3","text":"SEO and content: 30 to 35 percent. Paid advertising: 25 to 30 percent. Website and design: 10 to 15 percent."}]},{"_type":"block","_key":"1e9c2d72","style":"h2","children":[{"_type":"span","_key":"1056dcc8","text":"The Real Question Is Cost Per Acquisition"}]},{"_type":"block","_key":"ee2e2793","style":"normal","children":[{"_type":"span","_key":"db8b1437","text":"If a new client is worth $5,000 over their lifetime and you can acquire them for $300 in marketing spend, you should be spending as much as you possibly can at that rate."}]}]',
  'How Much Should You Spend on Marketing in 2026?',
  'No vague percentages. Here''s a real breakdown of marketing budgets for small and mid-size businesses in 2026.',
  datetime('now')
);