INSERT INTO ec_posts (id, slug, status, title, excerpt, body, meta_title, meta_description, published_at) VALUES (
  9,
  '7-signs-your-website-is-costing-you-customers',
  'published',
  '7 Signs Your Website Is Costing You Customers',
  'Most business owners assume that if their website is live it''s doing its job. But a website that looks outdated or works poorly can actively drive customers to your competitors.',
  '[{"_type":"block","_key":"529d9935","style":"h2","children":[{"_type":"span","_key":"6e21780f","text":"1. Your Site Loads in More Than 3 Seconds"}]},{"_type":"block","_key":"243ff5bd","style":"normal","children":[{"_type":"span","_key":"61cd235a","text":"Google''s data shows that 53 percent of mobile users abandon a site that takes longer than 3 seconds to load."}]},{"_type":"block","_key":"4e80ee33","style":"h2","children":[{"_type":"span","_key":"aa73b312","text":"2. It Doesn''t Look Right on a Phone"}]},{"_type":"block","_key":"f16202b7","style":"normal","children":[{"_type":"span","_key":"99e49921","text":"More than 60 percent of web traffic now comes from mobile devices."}]},{"_type":"block","_key":"81f30d4a","style":"h2","children":[{"_type":"span","_key":"fa628c95","text":"3. Your Contact Information Is Hard to Find"}]},{"_type":"block","_key":"96502930","style":"normal","children":[{"_type":"span","_key":"4360df33","text":"Your phone number should be in the header of every page. Your contact form should never be more than one click away."}]},{"_type":"block","_key":"baab7c59","style":"h2","children":[{"_type":"span","_key":"afd69ef8","text":"4. The Design Looks Like It''s from 2015"}]},{"_type":"block","_key":"f5208852","style":"normal","children":[{"_type":"span","_key":"60172640","text":"People judge a website''s credibility in about 50 milliseconds according to research from Carleton University."}]},{"_type":"block","_key":"0e0eccf2","style":"h2","children":[{"_type":"span","_key":"c59953d1","text":"5. There Are No Clear Calls to Action"}]},{"_type":"block","_key":"16a57967","style":"normal","children":[{"_type":"span","_key":"9c77e568","text":"Every core page on your site should have one clear primary action. Not five. One."}]},{"_type":"block","_key":"33f7abeb","style":"h2","children":[{"_type":"span","_key":"a26366ae","text":"6. You Have No Social Proof"}]},{"_type":"block","_key":"b56fd719","style":"normal","children":[{"_type":"span","_key":"40c82b79","text":"People trust other people more than they trust businesses. Reviews, testimonials, case studies are the signals that tell a skeptical visitor that real customers have been happy."}]},{"_type":"block","_key":"dd4535c3","style":"h2","children":[{"_type":"span","_key":"b113d49b","text":"7. Google Can''t Find You"}]},{"_type":"block","_key":"3b41fd34","style":"normal","children":[{"_type":"span","_key":"243dd347","text":"A website that search engines can''t find is invisible to potential customers who don''t already know your name."}]}]',
  '7 Signs Your Website Is Costing You Customers',
  'Is your website quietly turning away potential customers? Here are 7 warning signs that your site is costing you business.',
  datetime('now')
);