INSERT INTO ec_posts (id, slug, status, title, excerpt, body, meta_title, meta_description, published_at) VALUES (
  6,
  'what-does-an-seo-company-actually-do',
  'published',
  'What Does an SEO Company Actually Do?',
  'Most business owners have hired or considered hiring an SEO company without fully understanding what they actually do all day. This guide breaks down the real work behind SEO.',
  '[{"_type":"block","_key":"f5834dd8","style":"h2","children":[{"_type":"span","_key":"9bf0cd80","text":"They Start by Auditing Your Current Situation"}]},{"_type":"block","_key":"fec50997","style":"normal","children":[{"_type":"span","_key":"8f7ffb70","text":"Before anything else, a good SEO company looks at where you stand. This means running a technical audit of your website to find problems that are stopping search engines from properly reading your pages."}]},{"_type":"block","_key":"e7e2f5bf","style":"h2","children":[{"_type":"span","_key":"3bc0a7a9","text":"They Research the Keywords Your Customers Use"}]},{"_type":"block","_key":"a588110a","style":"normal","children":[{"_type":"span","_key":"f5b84618","text":"Keyword research is the foundation of every SEO strategy. A good agency doesn''t just guess at what people search for."}]},{"_type":"block","_key":"ab2587b3","style":"h2","children":[{"_type":"span","_key":"09d1bbe6","text":"They Fix Technical Problems on Your Site"}]},{"_type":"block","_key":"028fda6a","style":"normal","children":[{"_type":"span","_key":"1315fa16","text":"Technical SEO is the unglamorous work that makes everything else possible. If Google can''t crawl your site properly, your content doesn''t matter."}]},{"_type":"block","_key":"38c21f8e","style":"h2","children":[{"_type":"span","_key":"7a7298f1","text":"They Build and Optimize Your Content"}]},{"_type":"block","_key":"ecb7a43a","style":"normal","children":[{"_type":"span","_key":"c0a0c9e0","text":"Content is how you answer the questions your customers are already asking."}]},{"_type":"block","_key":"5e3f078e","style":"h2","children":[{"_type":"span","_key":"ce171c70","text":"They Build Authority Through Links"}]},{"_type":"block","_key":"83493a58","style":"normal","children":[{"_type":"span","_key":"64c44e7b","text":"Google treats links from other websites as votes of confidence. The more reputable sites that link to yours, the more Google trusts you."}]},{"_type":"block","_key":"4dc6477b","style":"h2","children":[{"_type":"span","_key":"5f58dc63","text":"They Track, Report, and Adjust"}]},{"_type":"block","_key":"50d58700","style":"normal","children":[{"_type":"span","_key":"b736c9f0","text":"Good SEO companies are obsessive about data. Every month, you should get a report showing your keyword rankings, organic traffic, and conversions from organic search."}]}]',
  'What Does an SEO Company Actually Do?',
  'Curious what an SEO company actually does with your money? Here''s a plain-English breakdown of the real work behind search engine optimization.',
  datetime('now')
);