// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface AboutPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  page_title?: string;
  route_path: string;
  meta_title?: string;
  meta_description?: string;
  intro_content?: PortableTextBlock[];
  intro_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  body_content?: PortableTextBlock[];
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface AppointmentPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  page_title?: string;
  route_path: string;
  meta_title?: string;
  meta_description?: string;
  default_location_slug?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface AudiologyService {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  body?: PortableTextBlock[];
  sort_order?: number;
  link_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ContactPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  page_title?: string;
  route_path: string;
  meta_title?: string;
  meta_description?: string;
  intro_content?: PortableTextBlock[];
  email_intro?: PortableTextBlock[];
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  question: string;
  answer?: PortableTextBlock[];
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HearingAidBrandCarousel {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  brand_slug: string;
  image_1?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_2?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_3?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_4?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_5?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_6?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_7?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_8?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_9?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_10?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_11?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_12?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_13?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_14?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  image_15?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HearingAidBrandFaq {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  brand_slug: string;
  question: string;
  answer?: PortableTextBlock[];
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HearingAidBrandModel {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  brand_slug: string;
  model_name: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  short_description?: PortableTextBlock[];
  key_features?: PortableTextBlock[];
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HearingAidBrandPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  brand_name: string;
  page_heading?: string;
  route_path: string;
  page_title?: string;
  meta_description?: string;
  intro_content?: PortableTextBlock[];
  models_heading?: string;
  assistive_devices_heading?: string;
  assistive_devices_content?: PortableTextBlock[];
  older_models_heading?: string;
  older_models_content?: PortableTextBlock[];
  faq_heading?: string;
  closing_heading?: string;
  closing_content?: PortableTextBlock[];
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HearingAidService {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  body?: PortableTextBlock[];
  sort_order?: number;
  link_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HomepageIntroCarouselImage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  image: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Homepage {
  id: string;
  slug: string | null;
  status: string;
  hero_eyebrow?: string;
  hero_headline?: string;
  hero_cta_text?: string;
  hero_cta_url?: string;
  intro_kicker?: string;
  intro_headline?: string;
  intro_body?: PortableTextBlock[];
  intro_primary_cta_text?: string;
  intro_primary_cta_url?: string;
  intro_secondary_cta_text?: string;
  intro_secondary_cta_url?: string;
  about_heading?: string;
  about_body?: PortableTextBlock[];
  locations_heading?: string;
  locations_body?: PortableTextBlock[];
  audiology_services_heading?: string;
  hearing_aid_services_heading?: string;
  faq_heading?: string;
  audiology_services_heading_continuation?: string;
  faq_body?: PortableTextBlock[];
  testimonials_heading?: string;
  hearing_aid_services_heading_continuation?: string;
  testimonials_subheading?: string;
  news_kicker?: string;
  news_heading?: string;
  news_body?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface InternalPageCta {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  heading?: string;
  body?: string;
  button_text?: string;
  button_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface LocationPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  location_slug: string;
  page_title?: string;
  meta_description?: string;
  hero_eyebrow?: string;
  hero_heading?: string;
  h1_eyebrow?: string;
  h1_heading?: string;
  intro_body?: PortableTextBlock[];
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  gallery_image_1?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  gallery_image_2?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  sort_order?: number;
  audiology_services_heading?: string;
  audiology_services_heading_continuation?: string;
  hearing_aid_services_heading?: string;
  hearing_aid_services_heading_continuation?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Location {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  address?: string;
  phone?: string;
  appointment_url?: string;
  directions_url?: string;
  google_maps_query?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  scheduler_embed_url?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  author?: string;
  content?: PortableTextBlock[];
  meta_title?: string;
  meta_description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ServicePage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  service_title?: string;
  route_path: string;
  page_title?: string;
  meta_description?: string;
  intro_content?: PortableTextBlock[];
  content_blocks?: unknown;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SiteSettings {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  phone?: string;
  phone_label?: string;
  appointment_url?: string;
  locations_summary?: string;
  footer_tagline?: string;
  copyright_year?: number;
  copyright_text?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface StaffMember {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  role?: string;
  locations?: string;
  location_slugs?: ("lansing-mi" | "portage-mi" | "anoka-mn" | "eden-prairie-mn" | "edina-mn" | "maple-grove-mn" | "mendota-heights-mn" | "new-ulm-mn" | "roseville-mn" | "willmar-mn" | "lake-wales-fl" | "sebring-fl" | "winter-haven-fl")[];
  profile_url?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface StaffPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  staff_slug: string;
  page_title?: string;
  meta_description?: string;
  intro_body?: PortableTextBlock[];
  audiology_services_heading?: string;
  audiology_services_heading_continuation?: string;
  hearing_aid_services_heading?: string;
  hearing_aid_services_heading_continuation?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Testimonial {
  id: string;
  slug: string | null;
  status: string;
  quote: PortableTextBlock[];
  name?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface UtilityPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  page_title?: string;
  route_path: string;
  meta_title?: string;
  meta_description?: string;
  content_body?: PortableTextBlock[];
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    about_pages: AboutPage;
    appointment_pages: AppointmentPage;
    audiology_services: AudiologyService;
    contact_pages: ContactPage;
    faqs: Faq;
    hearing_aid_brand_carousel_images: HearingAidBrandCarousel;
    hearing_aid_brand_faqs: HearingAidBrandFaq;
    hearing_aid_brand_models: HearingAidBrandModel;
    hearing_aid_brand_pages: HearingAidBrandPage;
    hearing_aid_services: HearingAidService;
    homepage_images: HomepageIntroCarouselImage;
    homepages: Homepage;
    internal_page_ctas: InternalPageCta;
    location_pages: LocationPage;
    locations: Location;
    pages: Page;
    posts: Post;
    service_pages: ServicePage;
    site_settings: SiteSettings;
    staff: StaffMember;
    staff_pages: StaffPage;
    testimonials: Testimonial;
    utility_pages: UtilityPage;
  }
}