/**
 * Per-article metadata for the blog posts (2026-09-22).
 *
 * WHY A ROUTE MAP, not props on the pages: the blog posts are generated by
 * scratchpad/gen-blog.py, so anything hand-added to those .astro files is lost on
 * the next regeneration — the same reason page-schema.ts is route-keyed.
 *
 * WHY NOT A HAND-WRITTEN BlogPosting BLOCK: emdash already emits one for any page
 * with pageType "article" (jsonld.ts -> buildBlogPostingJsonLd). Emitting our own
 * as well would put TWO BlogPosting blocks on the page — exactly the duplication
 * cleaned up on 2026-09-21. Feeding emdash's builder instead keeps it to one AND
 * preserves og:type="article" (emdash only skips the block if pageType is not
 * "article", which would also change the OG tag).
 *
 * LIMITS of emdash's builder, so nobody re-litigates them:
 *  - `author` is typed Person-only, so it cannot reference the existing
 *    `/dr-chris-duhon/#person` node by @id, and an Organization author is
 *    impossible. A plain Person name is what it supports.
 *  - `publisher` only appears if `siteName` is passed into the page context, and
 *    that is deliberately NOT passed (it is what emitted the duplicate bare
 *    `WebSite` block). publisher is optional for non-AMP Google Article results.
 *
 * Author confirmed by Vince 2026-09-22: Dr. Duhon.
 * DATES ARE DELIBERATELY ABSENT — neither post displays a date anywhere, and no
 * publication date has been confirmed. Add `publishedTime`/`modifiedTime` here
 * (ISO 8601) once the real dates are known; emdash drops undefined values.
 */
export interface ArticleMeta {
	author?: string;
	publishedTime?: string;
	modifiedTime?: string;
}

export const ARTICLE_META: Record<string, ArticleMeta> = {
	"/best-way-to-clean-ears/": { author: "Dr. Chris Duhon, AuD" },
	"/hearing-aids-for-tinnitus/": { author: "Dr. Chris Duhon, AuD" },
};

/** Article metadata for a pathname, tolerant of a missing trailing slash. */
export function articleMetaForPath(pathname: string): ArticleMeta | undefined {
	const p = pathname.endsWith("/") ? pathname : `${pathname}/`;
	return ARTICLE_META[p];
}
