// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Brand {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  logo?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  sort_order?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface FaqItem {
  id: string;
  slug: string | null;
  status: string;
  question: string;
  answer?: string;
  sort_order?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HearingAidService {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  link_url?: string;
  sort_order?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ProtectionType {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  sort_order?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  link_url?: string;
  sort_order?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SiteConfiguration {
  id: string;
  slug: string | null;
  status: string;
  phone?: string;
  address_line1?: string;
  address_line2?: string;
  city_state?: string;
  email?: string;
  book_url?: string;
  hero_heading?: string;
  hero_subtext?: string;
  hero_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  about_tagline?: string;
  about_heading?: string;
  about_text?: string;
  about_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  team_heading?: string;
  team_text?: string;
  hours_mon?: string;
  hours_tue?: string;
  hours_wed?: string;
  hours_thu?: string;
  hours_fri?: string;
  hours_sat?: string;
  hours_sun?: string;
  map_embed_url?: string;
  services_heading?: string;
  services_subtext?: string;
  hearing_aids_heading?: string;
  hearing_aids_subtext?: string;
  protection_heading?: string;
  protection_subtext?: string;
  testimonials_heading?: string;
  faq_heading?: string;
  news_heading?: string;
  facebook_url?: string;
  instagram_url?: string;
  twitter_url?: string;
  footer_tagline?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface TeamMember {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  role?: string;
  bio?: string;
  photo?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  sort_order?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Testimonial {
  id: string;
  slug: string | null;
  status: string;
  patient_name: string;
  rating?: string;
  review?: string;
  avatar?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  sort_order?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    brands: Brand;
    faq: FaqItem;
    hearing_aids: HearingAidService;
    hearing_protection: ProtectionType;
    pages: Page;
    posts: Post;
    services: Service;
    site_config: SiteConfiguration;
    team: TeamMember;
    testimonials: Testimonial;
  }
}