// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit } from "emdash";

export interface Archive {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  seo_title?: string;
  meta_description?: string;
  canonical?: string;
  route: string;
  body_class?: string;
  stylesheets?: unknown;
  head_html?: string;
  body_html: string;
  content_type?: string;
  source_file?: string;
  robots?: string;
  seo_head_html?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Article {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  seo_title?: string;
  meta_description?: string;
  canonical?: string;
  route: string;
  body_class?: string;
  stylesheets?: unknown;
  head_html?: string;
  body_html: string;
  content_type?: string;
  source_file?: string;
  robots?: string;
  seo_head_html?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Audiologist {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  seo_title?: string;
  meta_description?: string;
  canonical?: string;
  route: string;
  body_class?: string;
  stylesheets?: unknown;
  head_html?: string;
  body_html: string;
  content_type?: string;
  source_file?: string;
  robots?: string;
  seo_head_html?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HearingAidPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  seo_title?: string;
  meta_description?: string;
  canonical?: string;
  route: string;
  body_class?: string;
  stylesheets?: unknown;
  head_html?: string;
  body_html: string;
  content_type?: string;
  source_file?: string;
  robots?: string;
  seo_head_html?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  seo_title?: string;
  meta_description?: string;
  canonical?: string;
  route: string;
  body_class?: string;
  stylesheets?: unknown;
  head_html?: string;
  body_html: string;
  content_type?: string;
  source_file?: string;
  robots?: string;
  seo_head_html?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  seo_title?: string;
  meta_description?: string;
  canonical?: string;
  route: string;
  body_class?: string;
  stylesheets?: unknown;
  head_html?: string;
  body_html: string;
  content_type?: string;
  source_file?: string;
  robots?: string;
  seo_head_html?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Testimonial {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  seo_title?: string;
  meta_description?: string;
  canonical?: string;
  route: string;
  body_class?: string;
  stylesheets?: unknown;
  head_html?: string;
  body_html: string;
  content_type?: string;
  source_file?: string;
  robots?: string;
  seo_head_html?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface UtilityPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  seo_title?: string;
  meta_description?: string;
  canonical?: string;
  route: string;
  body_class?: string;
  stylesheets?: unknown;
  head_html?: string;
  body_html: string;
  content_type?: string;
  source_file?: string;
  robots?: string;
  seo_head_html?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    archives: Archive;
    articles: Article;
    audiologists: Audiologist;
    hearing_aids: HearingAidPage;
    pages: Page;
    services: Service;
    testimonials: Testimonial;
    utility_pages: UtilityPage;
  }
}