// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface InternalPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  route: string;
  meta_title?: string;
  meta_description?: string;
  content?: PortableTextBlock[];
  body_html?: string;
  excerpt?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  featured_image_path?: string;
  template_family?: string;
  shell_key?: string;
  schema_json?: string;
  sitemap_group?: string;
  sitemap_lastmod?: string;
  include_in_sitemap?: boolean;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  route: string;
  meta_title?: string;
  meta_description?: string;
  content?: PortableTextBlock[];
  body_html?: string;
  excerpt?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  featured_image_path?: string;
  template_family?: string;
  shell_key?: string;
  schema_json?: string;
  sitemap_group?: string;
  sitemap_lastmod?: string;
  include_in_sitemap?: boolean;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  route: string;
  meta_title?: string;
  meta_description?: string;
  content?: PortableTextBlock[];
  body_html?: string;
  excerpt?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  featured_image_path?: string;
  template_family?: string;
  shell_key?: string;
  schema_json?: string;
  sitemap_group?: string;
  sitemap_lastmod?: string;
  include_in_sitemap?: boolean;
  sort_order?: number;
  author_name?: string;
  published_label?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface TeamMember {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  route: string;
  meta_title?: string;
  meta_description?: string;
  content?: PortableTextBlock[];
  body_html?: string;
  excerpt?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  featured_image_path?: string;
  template_family?: string;
  shell_key?: string;
  schema_json?: string;
  sitemap_group?: string;
  sitemap_lastmod?: string;
  include_in_sitemap?: boolean;
  sort_order?: number;
  credentials?: string;
  job_title?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    internal_pages: InternalPage;
    pages: Page;
    posts: Post;
    team_members: TeamMember;
  }
}