// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit } from "emdash";

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  question?: string;
  answer?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface FormSubmission {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  name?: string;
  email?: string;
  phone?: string;
  message?: string;
  read_status?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  description?: string;
  duration?: string;
  format?: string;
  price?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Testimonial {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  quote?: string;
  role?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    faqs: Faq;
    form_submissions: FormSubmission;
    services: Service;
    testimonials: Testimonial;
  }
}