// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit } from "emdash";

// ============================================================
// SINGLETONS (one row per collection — slug is the entry id)
// ============================================================

export interface SiteSettings {
  id: string;
  slug: string | null;
  status: string;
  phone?: string;
  email?: string;
  address_street?: string;
  address_city_state?: string;
  hours_mon_thu?: string;
  hours_fri?: string;
  google_maps_url?: string;
  facebook_url?: string;
  google_review_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Homepage {
  id: string;
  slug: string | null;
  status: string;
  // Hero
  hero_eyebrow?: string;
  hero_heading?: string;
  hero_lead?: string;
  hero_cta_text?: string;
  hero_image?: { meta?: { storageKey?: string }; src?: string };
  // Stats strip
  reviews_count?: string;
  // About
  about_eyebrow?: string;
  about_heading?: string;
  about_body?: string;
  about_body2?: string;
  about_badge_title?: string;
  about_image?: { meta?: { storageKey?: string }; src?: string };
  about_years_num?: string;
  about_years_label?: string;
  about_doctors_num?: string;
  about_doctors_label?: string;
  about_brands_num?: string;
  about_brands_label?: string;
  // Team intro
  team_eyebrow?: string;
  team_heading?: string;
  team_subhead?: string;
  // Cochlear
  cochlear_eyebrow?: string;
  cochlear_heading?: string;
  cochlear_body?: string;
  // Diagnostic services
  diag_eyebrow?: string;
  diag_heading?: string;
  diag_subhead?: string;
  // Hearing aid services
  ha_eyebrow?: string;
  ha_heading?: string;
  // Brands intro
  brands_eyebrow?: string;
  brands_heading?: string;
  brands_subhead?: string;
  // Testimonials intro
  testimonials_eyebrow?: string;
  testimonials_heading?: string;
  // FAQ intro
  faq_eyebrow?: string;
  faq_heading?: string;
  faq_subhead?: string;
  // Blog preview intro
  blog_eyebrow?: string;
  blog_heading?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface AboutPage {
  id: string;
  slug: string | null;
  status: string;
  story_eyebrow?: string;
  story_heading?: string;
  story_body1?: string;
  story_body2?: string;
  story_image?: { meta?: { storageKey?: string }; src?: string };
  story_image_caption?: string;
  story_stat1_num?: string;
  story_stat1_label?: string;
  story_stat2_num?: string;
  story_stat2_label?: string;
  story_stat3_num?: string;
  story_stat3_label?: string;
  philosophy_eyebrow?: string;
  philosophy_heading?: string;
  philosophy_body1?: string;
  philosophy_body2?: string;
  philosophy_body3?: string;
  philosophy_body4?: string;
  philosophy_image?: { meta?: { storageKey?: string }; src?: string };
  philosophy_image_caption?: string;
  team_eyebrow?: string;
  team_heading?: string;
  team_subhead?: string;
  meta_title?: string;
  meta_description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ContactPage {
  id: string;
  slug: string | null;
  status: string;
  intro_eyebrow?: string;
  intro_heading?: string;
  intro_body1?: string;
  intro_body2?: string;
  meta_title?: string;
  meta_description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

// ============================================================
// COLLECTIONS (multiple rows)
// ============================================================

export interface TeamMember {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  role?: string;
  credentials?: string;
  bio_short?: string;
  bio_full?: string;
  bio_p1?: string;
  bio_p2?: string;
  bio_p3?: string;
  bio_p4?: string;
  education?: string;
  photo?: { meta?: { storageKey?: string }; src?: string };
  meta_title?: string;
  meta_description?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface BlogPost {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  excerpt?: string;
  content?: string;
  featured_image?: { meta?: { storageKey?: string }; src?: string };
  featured_image_url?: string;
  author?: string;
  date?: string;
  category?: string;
  read_time?: string;
  meta_title?: string;
  meta_description?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Testimonial {
  id: string;
  slug: string | null;
  status: string;
  quote?: string;
  author?: string;
  city?: string;
  rating?: number;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Faq {
  id: string;
  slug: string | null;
  status: string;
  question?: string;
  answer?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ServicePage {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  meta_title?: string;
  meta_description?: string;
  lead?: string;
  content?: string;
  hero_image?: { meta?: { storageKey?: string }; src?: string };
  hero_image_url?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface BrandPage {
  id: string;
  slug: string | null;
  status: string;
  brand_name?: string;
  title?: string;
  meta_title?: string;
  meta_description?: string;
  lead?: string;
  content?: string;
  hero_image_url?: string;
  brand_logo?: { meta?: { storageKey?: string }; src?: string };
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface LocationPage {
  id: string;
  slug: string | null;
  status: string;
  location_name?: string;
  title?: string;
  meta_title?: string;
  meta_description?: string;
  lead?: string;
  content?: string;
  hero_image_url?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ResourcePage {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  meta_title?: string;
  meta_description?: string;
  lead?: string;
  content?: string;
  hero_image_url?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ConditionPage {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  meta_title?: string;
  meta_description?: string;
  lead?: string;
  content?: string;
  hero_image_url?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface LegalPage {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  meta_title?: string;
  meta_description?: string;
  content?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    site_settings: SiteSettings;
    homepage: Homepage;
    about_page: AboutPage;
    contact_page: ContactPage;
    team_members: TeamMember;
    blog_posts: BlogPost;
    testimonials: Testimonial;
    faqs: Faq;
    service_pages: ServicePage;
    brand_pages: BrandPage;
    location_pages: LocationPage;
    resource_pages: ResourcePage;
    condition_pages: ConditionPage;
    legal_pages: LegalPage;
  }
}
