// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface About {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content: PortableTextBlock[];
  featured_image: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  meta_title: string;
  meta_description: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface BlogPost {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  publish_date: string;
  author: string;
  category: string;
  content: PortableTextBlock[];
  featured_image: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  meta_title: string;
  meta_description: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ContactPage {
  id: string;
  slug: string | null;
  status: string;
  content_body: PortableTextBlock[];
  meta_title: string;
  meta_description: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HearingAidBrand {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content: PortableTextBlock[];
  meta_title: string;
  meta_description: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Homepage {
  id: string;
  slug: string | null;
  status: string;
  hero_intro: string;
  hero_cta: string;
  intro_section_title: string;
  intro_body: PortableTextBlock[];
  badge_1: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  badge_2: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  badge_3: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  audiology_services_featured_image: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  audiology_services_body: PortableTextBlock[];
  hearing_aids_protection_solutions_image: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hearing_aids_protection_solutions_body: PortableTextBlock[];
  hearing_aid_brand_image_1: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hearing_aid_brand_image_2: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hearing_aid_brand_image_3: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hearing_aid_brand_image_4: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hearing_aid_brand_image_5: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hearing_aid_brand_image_6: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hearing_aid_brand_image_7: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  testimonial_section_title: string;
  testimonial_eyebrow: string;
  faq_section_title: string;
  faq_eyebrow: string;
  faq_description: PortableTextBlock[];
  faq_content: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Location {
  id: string;
  slug: string | null;
  status: string;
  location_name: string;
  address: PortableTextBlock[];
  phone_number: PortableTextBlock[];
  phone_number_url: string;
  office_hours: string;
  map_url: string;
  map_widget: string;
  location_image_1: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  location_image_2: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  location_image_3: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  location_image_4: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  location_image_5: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  location_image_6: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hero_intro: string;
  h1_title: string;
  location_body: PortableTextBlock[];
  location_trust_badge_1: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  location_trust_badge_2: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  featured_image: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  meta_title: string;
  meta_description: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content: PortableTextBlock[];
  meta_title: string;
  meta_description: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface TeamMember {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  team_title: string;
  location: string;
  biography: PortableTextBlock[];
  featured_image: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  meta_title: string;
  meta_description: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface UtilityPage {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content: PortableTextBlock[];
  meta_title: string;
  meta_description: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    about: About;
    blog_post: BlogPost;
    contact_page: ContactPage;
    hearing_aid_brands: HearingAidBrand;
    homepage: Homepage;
    locations: Location;
    services: Service;
    team: TeamMember;
    utility_pages: UtilityPage;
  }
}