const fs = require('fs');
const path = require('path');
const { chromium } = require('playwright');
const BASE = 'https://www.jc-audiology.com';
const HOSTS = new Set(['www.jc-audiology.com','jc-audiology.com']);
const OUT = path.resolve('local-copy');
const ASSET_ROOT = path.join(OUT, 'assets');
function ensureDir(p){ fs.mkdirSync(p,{recursive:true}); }
function hash(s){ let h=2166136261; for(let i=0;i<s.length;i++){ h^=s.charCodeAt(i); h = Math.imul(h,16777619);} return (h>>>0).toString(16); }
function normalizePageUrl(u){ try{ const x = new URL(u, BASE); if(!HOSTS.has(x.hostname)) return null; if(!/^https?:$/.test(x.protocol)) return null; if(x.pathname.includes('/feed/')) return null; if(x.pathname.startsWith('/category/')) return null; x.hash=''; x.search=''; if(!x.pathname.endsWith('/')) x.pathname += '/'; return x.toString().replace('http://','https://'); }catch{ return null; } }
function routePathFromUrl(u){ const x = new URL(u); let p = x.pathname.replace(/^\/+|\/+$/g,''); if(!p) return OUT; return path.join(OUT, p); }
function rel(fromFile, toFile){ return path.relative(path.dirname(fromFile), toFile).split(path.sep).join('/'); }
function safeName(url){ const u = new URL(url); const base = path.basename(u.pathname) || 'asset'; const clean = base.replace(/[^a-zA-Z0-9._-]+/g,'-'); return `${hash(url)}-${clean}`; }
function typeDir(ct, pathname){ const ext = path.extname(pathname).toLowerCase(); if((ct||'').includes('text/css') || ext==='.css') return 'styles'; if((ct||'').includes('javascript') || ['.js','.mjs'].includes(ext)) return 'js'; if((ct||'').startsWith('image/') || ['.png','.jpg','.jpeg','.gif','.svg','.webp','.avif','.ico'].includes(ext)) return 'media'; if((ct||'').startsWith('font/') || ['.woff','.woff2','.ttf','.otf','.eot'].includes(ext)) return 'fonts'; if(['.mp4','.webm','.mov','.mp3','.wav'].includes(ext)) return 'media'; return 'misc'; }
async function getSitemapUrls(){
  return [
    normalizePageUrl(`${BASE}/`),
    normalizePageUrl(`${BASE}/blog/`),
  ].filter(Boolean);
}
async function mirror(){ ensureDir(OUT); ensureDir(ASSET_ROOT); const browser = await chromium.launch({headless:true}); const context = await browser.newContext({ viewport: { width: 1440, height: 2200 } }); const assetMap = new Map(); context.on('response', async (resp)=>{ try{ const url = resp.url(); if(!/^https?:\/\//i.test(url)) return; const rt = resp.request().resourceType(); if(!['stylesheet','script','image','font','media','other'].includes(rt)) return; if(assetMap.has(url)) return; const status = resp.status(); if(status < 200 || status >= 400) return; const body = await resp.body(); const ct = resp.headers()['content-type'] || ''; const dir = typeDir(ct, new URL(url).pathname); const target = path.join(ASSET_ROOT, dir, safeName(url)); ensureDir(path.dirname(target)); fs.writeFileSync(target, body); assetMap.set(url, target);} catch {} });
const initial = await getSitemapUrls(); const queue = [...initial]; const seen = new Set();
while(queue.length){ const url = queue.shift(); if(seen.has(url)) continue; seen.add(url); const page = await context.newPage(); try{ await page.goto(url, {waitUntil:'networkidle', timeout:120000}); const current = normalizePageUrl(page.url()) || url; let html = await page.content(); const links = await page.$$eval('a[href]', els => els.map(a=>a.getAttribute('href')).filter(Boolean)); for(const href of links){ const n = normalizePageUrl(new URL(href, current).toString()); if(n && !seen.has(n) && !queue.includes(n)) queue.push(n);} const outDir = routePathFromUrl(current); ensureDir(outDir); const outFile = path.join(outDir, 'index.html'); const route='/' + new URL(current).pathname.replace(/^\/+|\/+$/g,'') + '/'; const canonical = route==='//'?'/':route; const cTag = `<link rel="canonical" href="${canonical}" />`; html = /<link[^>]+rel=["']canonical["']/i.test(html) ? html.replace(/<link[^>]+rel=["']canonical["'][^>]*>/ig,cTag) : html.replace(/<\/head>/i,`${cTag}\n</head>`); html = html.replace(/<form\b([^>]*)>/ig,(m,attrs)=>{ let a=attrs; a=/onsubmit=/i.test(a)?a.replace(/onsubmit=("[^"]*"|'[^']*')/ig,'onsubmit="return false;"'):a+' onsubmit="return false;"'; a=/action=/i.test(a)?a.replace(/action=("[^"]*"|'[^']*')/ig,'action="#"'):a+' action="#"'; return `<form${a}>`;});
html = html.replace(/\b(href|src)=(["'])([^"']+)\2/ig,(m,attr,q,val)=>{ if(/^(#|mailto:|tel:|javascript:|data:)/i.test(val)) return m; try{ const abs = new URL(val, current).toString(); if(assetMap.has(abs)) return `${attr}=${q}${rel(outFile, assetMap.get(abs))}${q}`; const n = normalizePageUrl(abs); if(n){ const p = path.join(routePathFromUrl(n), 'index.html'); return `${attr}=${q}${rel(outFile,p)}${q}`; } }catch{} return m; });
html = html.replace(/\bsrcset=(["'])([^"']+)\1/ig,(m,q,content)=>`srcset=${q}${content.split(',').map(x=>x.trim()).filter(Boolean).map(token=>{ const bits=token.split(/\s+/); let u=bits[0]; const desc=bits.slice(1).join(' '); try{const abs=new URL(u,current).toString(); if(assetMap.has(abs)) u=rel(outFile,assetMap.get(abs));}catch{} return desc?`${u} ${desc}`:u; }).join(', ')}${q}`);
html = html.replace(/elementor/ig,'astro').replace(/\bwp-/g,'astro-').replace(/\bwp_/g,'astro_'); fs.writeFileSync(outFile, html, 'utf8'); console.log(`saved ${current}`); await page.waitForTimeout(250);
} catch (e) { console.log(`failed ${url}: ${e.message}`);} finally { await page.close(); }}
for (const fp of fs.readdirSync(ASSET_ROOT, {recursive:true})) { const full = path.join(ASSET_ROOT, fp); if(!fs.existsSync(full)||fs.statSync(full).isDirectory()) continue; if(!/\.(css|js|mjs|html)$/i.test(full)) continue; try{ let t=fs.readFileSync(full,'utf8'); t=t.replace(/elementor/ig,'astro').replace(/\bwp-/g,'astro-').replace(/\bwp_/g,'astro_'); for(const [u,p] of assetMap.entries()){ t=t.split(u).join(path.relative(path.dirname(full),p).split(path.sep).join('/')); } fs.writeFileSync(full,t,'utf8'); }catch{} }
const pages=[]; (function walk(dir){ for(const ent of fs.readdirSync(dir,{withFileTypes:true})){ const full=path.join(dir,ent.name); if(ent.isDirectory()) walk(full); else if(ent.isFile()&&ent.name.toLowerCase()==='index.html'){ const relp=path.relative(OUT,full).split(path.sep).join('/'); if(relp==='index.html') continue; pages.push({route:'/'+relp.replace(/\/index\.html$/,'')+'/',relp}); }}})(OUT); pages.sort((a,b)=>a.route.localeCompare(b.route)); fs.writeFileSync(path.join(OUT,'all-pages.html'),`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Local Copy Page Index</title></head><body><h1>Local Copy Page Index</h1>${pages.map(p=>`<a href="./${p.relp}">${p.route}</a><br>`).join('')}</body></html>`,'utf8');
fs.writeFileSync(path.join(OUT,'export-manifest.json'),JSON.stringify({base:BASE,pages:[...seen].sort(),pageCount:seen.size,assetCount:assetMap.size,generatedAt:new Date().toISOString()},null,2),'utf8'); await browser.close(); console.log(`done pages=${seen.size} assets=${assetMap.size}`); }
mirror().catch(e=>{ console.error(e); process.exit(1); });
