// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface AudiologyServicesSection {
  id: string;
  slug: string | null;
  status: string;
  section_key: string;
  h2_section_title: string;
  content_body?: PortableTextBlock[];
  section_featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  service_cards?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Blog {
  id: string;
  slug: string | null;
  status: string;
  post_title: string;
  route: string;
  meta_title?: string;
  meta_description?: string;
  category?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  body_content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ContactPage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  route: string;
  meta_title?: string;
  meta_description?: string;
  section_featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface GlobalSection {
  id: string;
  slug: string | null;
  status: string;
  section_key: string;
  title: string;
  summary?: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HearingAidBrand {
  id: string;
  slug: string | null;
  status: string;
  brand_name: string;
  route: string;
  meta_title?: string;
  meta_description?: string;
  body_content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HearingAidServicesSection {
  id: string;
  slug: string | null;
  status: string;
  section_key: string;
  section_featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  h2_section_title: string;
  content_body?: PortableTextBlock[];
  learn_more_url?: string;
  accordion_items?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HearingAidsSection {
  id: string;
  slug: string | null;
  status: string;
  section_key: string;
  h2_section_title: string;
  section_subheading?: string;
  service_cards?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Homepage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  route: string;
  meta_title?: string;
  meta_description?: string;
  hero_title?: string;
  hero_subtext?: string;
  schedule_appointment_url?: string;
  cta_text?: PortableTextBlock[];
  trust_badge_1?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  trust_badge_2?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  trust_badge_3?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  trust_badge_4?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  trust_badge_5?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  trust_badge_6?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  trust_badge_7?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  trust_badge_8?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  about_featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  about_h1_section_title?: string;
  about_h2_section_title?: string;
  about_content_body?: PortableTextBlock[];
  about_us_url?: string;
  testimonials_subheading?: string;
  testimonials_h2_section_title?: string;
  faq_h2_section_title?: string;
  faq_body_content?: PortableTextBlock[];
  faq_items?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface OfficeInfoMapCta {
  id: string;
  slug: string | null;
  status: string;
  section_key: string;
  clinic_name: PortableTextBlock[];
  content_body?: PortableTextBlock[];
  address: string;
  address_url: string;
  hours?: PortableTextBlock[];
  phone_number?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SinglePageWithSidebar {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  route: string;
  meta_title?: string;
  meta_description?: string;
  body_content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface SitemapPage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  route: string;
  meta_title?: string;
  meta_description?: string;
  body_content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface StaffMember {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  job_title?: string;
  route: string;
  meta_title?: string;
  meta_description?: string;
  bio?: PortableTextBlock[];
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface TinnitusCta {
  id: string;
  slug: string | null;
  status: string;
  section_key: string;
  h2_section_title: string;
  content_body?: PortableTextBlock[];
  section_featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  accordion_items?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface UtilityPage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  route: string;
  meta_title?: string;
  meta_description?: string;
  body_content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    audiology_services_sections: AudiologyServicesSection;
    blogs: Blog;
    contact_pages: ContactPage;
    global_sections: GlobalSection;
    hearing_aid_brands: HearingAidBrand;
    hearing_aid_services_sections: HearingAidServicesSection;
    hearing_aids_sections: HearingAidsSection;
    homepage: Homepage;
    office_info_map_ctas: OfficeInfoMapCta;
    single_page_with_sidebar: SinglePageWithSidebar;
    sitemap_pages: SitemapPage;
    staff: StaffMember;
    tinnitus_ctas: TinnitusCta;
    utility_pages: UtilityPage;
  }
}