// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Audiologist {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  credentials?: string;
  title?: string;
  photo_src?: string;
  photo_alt?: string;
  bio?: string;
  location_slug?: string;
  location_label?: string;
  location_url?: string;
  em_class?: string;
  meta_title?: string;
  meta_description?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ContentPage {
  id: string;
  slug: string | null;
  status: string;
  page_type?: string;
  meta_title?: string;
  meta_description?: string;
  content?: string;
  featured_image_src?: string;
  featured_image_alt?: string;
  sort_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Location {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  page_slug?: string;
  address_line1?: string;
  address_line2?: string;
  city_state_zip?: string;
  phone?: string;
  phone_href?: string;
  hours?: string;
  map_embed_src?: string;
  directions_url?: string;
  booking_iframe_src?: string;
  acquisition_banner_html?: string;
  tab_index?: number;
  meta_title?: string;
  meta_description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface StaticPage {
  id: string;
  slug: string | null;
  status: string;
  meta_title?: string;
  meta_description?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    audiologists: Audiologist;
    content_pages: ContentPage;
    locations: Location;
    pages: Page;
    posts: Post;
    static_pages: StaticPage;
  }
}